DigitalPurchasing.Web/Controllers/AdminController.cs
using System.IO;
using System.Threading.Tasks;
using DigitalPurchasing.Core.Interfaces;
using DigitalPurchasing.Web.Core;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DigitalPurchasing.Web.Controllers
{
    [AuthorizeAdmin]
    public class AdminController : Controller
    {
        private readonly IAdminService _adminService;
        private readonly IFileService _fileService;

        public AdminController(
            IAdminService adminService,
            IFileService fileService)
        {
            _adminService = adminService;
            _fileService = fileService;
        }

        public async Task<IActionResult> Index()
        {
            var vm = await _adminService.GetDashboard();
            return View(vm);
        }

        public async Task<IActionResult> Companies()
        {
            var vm = await _adminService.GetCompanies();
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> UploadTerms(IFormFile file)
        {
            if (file == null)
            {
                return RedirectToAction(nameof(Index));
            }

            using (var ms = new MemoryStream())
            {
                await file.CopyToAsync(ms);
                _fileService.ReplaceTermsFile(file.FileName, ms.ToArray(), file.ContentType);
            }

            TempData["SuccessMessage"] = "\"Условия использования\" загружены";

            return RedirectToAction(nameof(Index));
        }

        public IActionResult DownloadTerms()
        {
            var termsFile = _fileService.GetTermsFile();

            if (termsFile == null) return NotFound();

            return File(termsFile.Bytes, termsFile.ContentType, termsFile.FileName);
        }
    }
}

DigitalPurchasing.Web/Controllers/ColumnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DigitalPurchasing.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace DigitalPurchasing.Web.Controllers
{
    public class ColumnController : BaseController
    {
        private readonly IColumnNameService _columnNameService;

        public ColumnController(IColumnNameService columnNameService) => _columnNameService = columnNameService;

        public IActionResult Index() => View();

        public IActionResult Data()
        {
            var names = _columnNameService.GetAllNames();
            return Json(names);
        }

        [HttpPost]
        public IActionResult SaveData([FromBody] ColumnResponse model)
        {
            _columnNameService.SaveAllNames(model);
            return Ok();
        }
    }
}

DigitalPurchasing.Web/Controllers/DashboardController.cs
using System;
using System.Threading.Tasks;
using DigitalPurchasing.Core.Extensions;
using DigitalPurchasing.Core.Interfaces;
using DigitalPurchasing.Web.ViewModels.Dashboard;
using Microsoft.AspNetCore.Mvc;

namespace DigitalPurchasing.Web.Controllers
{
    public class DashboardController : BaseController
    {
        private readonly IDashboardService _dashboardService;

        public DashboardController(IDashboardService dashboardService)
            => _dashboardService = dashboardService;

        public async Task<IActionResult> Index()
        {
            var companyId = User.CompanyId();
            var nowDate = DateTime.UtcNow.Date;
            var daysInMonth = DateTime.DaysInMonth(nowDate.Year, nowDate.Month);
            var fromDate = new DateTime(nowDate.Year, nowDate.Month, 1, 0, 0, 0);
            var toDate = new DateTime(nowDate.Year, nowDate.Month, daysInMonth, 23, 59, 59);
            var requestStatuses = await _dashboardService.GetRequestStatuses(companyId, fromDate, toDate);
            var suppliers = await _dashboardService.GetTopSuppliers(companyId, fromDate, toDate);

            var vm = new DashboardIndexVm
            {
                FromDate = fromDate,
                ToDate = toDate,
                RequestStatuses = requestStatuses,
                Suppliers = suppliers
            };

            return View(vm);
        }
    }
}

DigitalPurchasing.Web/Views/Shared/_AlertDanger.cshtml
@model string

@if (!string.IsNullOrEmpty(Model))
{
    <div class="alert alert-danger alert-dismissible" role="alert" style="margin-top: 15px;">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

DigitalPurchasing.Web/Views/Shared/_AlertSuccess.cshtml
@model string

@if (!string.IsNullOrEmpty(Model))
{
    <div class="alert alert-success alert-dismissible" role="alert" style="margin-top: 15px;">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

DigitalPurchasing.Web/Views/Shared/_CompanyNamePartial.cshtml
@using DigitalPurchasing.Core
@using DigitalPurchasing.Models.Identity
@using Microsoft.AspNetCore.Identity

@inject SignInManager<User> SignInManager

@if (SignInManager.IsSignedIn(User) && User.IsInRole(Consts.Roles.CompanyOwner))
{
    var companyName = User.FindFirst(CustomClaimTypes.CompanyName).Value;
    if (string.IsNullOrEmpty(companyName))
    {
        <div class="alert alert-warning alert-dismissible" role="alert" style="margin-top: 15px;">
            Пожалуйста укажите название вашей организации в <a asp-area="Identity" asp-page="/Account/Manage/Company">профиле</a>
        </div>
    }
}

DigitalPurchasing.Web/Views/Shared/_CompetitionListReports.cshtml
@using DigitalPurchasing.Core.Interfaces;
@using DigitalPurchasing.Web.Controllers
@model IEnumerable<SSReportSimple>

@if (Model.Any())
{
    <div class="row">
        <div class="col-md-6">
            <table class="table">
                <thead>
                    <tr>
                        <th>Дата и время подтверждения</th>
                        <th>Вариант выбора</th>
                        <th>Общая сумма</th>
                        <th>Валюта</th>
                        <th>Выбор подтвердил</th>
                        <th>Отчет о выборе поставщиков</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var report in Model)
                    {
                        <tr>
                            <td>@report.CreatedOn.ToString("dd.MM.yyyy HH:mm")</td>
                            <td>@report.SelectedVariantNumber</td>
                            <td>@report.SelectedVariantTotalPrice.ToString("N")</td>
                            <td>@report.Currency</td>
                            <td>@report.SelectedBy</td>
                            <td><a href="@Url.Action(nameof(CompetitionListController.Report), new { reportId = report.ReportId })">Скачать</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

DigitalPurchasing.Web/Views/Shared/_ConfirmEmailPartial.cshtml
@using DigitalPurchasing.Models.Identity
@using Microsoft.AspNetCore.Identity

@inject UserManager<User> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
}

@if (user != null && !user.EmailConfirmed)
{
    <div class="alert alert-warning alert-dismissible" role="alert" style="margin-top: 15px;">
        Пожалуйста подтвердите адрес вашу электронную почты в <a asp-area="Identity" asp-page="/Account/Manage/Index">профиле</a>
    </div>
}

DigitalPurchasing.Web/Views/Shared/_Layout.cshtml
@using DigitalPurchasing.Core
@{
    const string appName = "Digital Purchasing";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @appName</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/bundles/custom.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/solid.css" integrity="sha384-VGP9aw4WtGH/uPAOseYxZ+Vz/vaTb1ehm1bwx92Fm8dTrE+3boLfF1SpAtB1z7HW" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/regular.css" integrity="sha384-ZlNfXjxAqKFWCwMwQFGhmMh3i89dWDnaFU2/VZg9CvsMGA7hXHQsPIqS+JIAmgEq" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/fontawesome.css" integrity="sha384-1rquJLNOM3ijoueaaeS5m+McXPJCGdr5HcA03/VHXxcp2kX2sUrQDmFc3jR5i/C7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.9/css/select2.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">@appName</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Dashboard" asp-action="Index">Главная</a></li>
                        if (User.IsInRole(Consts.Roles.Admin))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Админка&nbsp;<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Admin" asp-action="Index">Главная</a></li>
                                    <li><a asp-area="" asp-controller="Admin" asp-action="Companies">Организации</a></li>
                                    <li><a href="/hangfire">Hangfire</a></li>
                                </ul>
                            </li>
                        }
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Документы&nbsp;<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="PurchaseRequest" asp-action="Index">Заявки клиентов</a></li>
                                <li><a asp-area="" asp-controller="QuotationRequest" asp-action="Index">Запросы предложений</a></li>
                                <li><a asp-area="" asp-controller="CompetitionList" asp-action="Index">Конкурентные листы</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Справочники&nbsp;<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Supplier" asp-action="Index">Поставщики</a></li>
                                <li><a asp-area="" asp-controller="Customer" asp-action="Index">Клиенты</a></li>
                                <li><a asp-area="" asp-controller="Nomenclature" asp-action="Index">Наименования материалов</a></li>
                                <li><a asp-area="" asp-controller="NomenclatureCategory" asp-action="Index">Категории закупок</a></li>
                                <li><a asp-area="" asp-controller="Uom" asp-action="Index">Единицы измерения</a></li>
                                <li><a asp-area="" asp-controller="Column" asp-action="Index">Соответсвия названий колонок</a></li>
                            </ul>
                        </li>
                        <li><a asp-area="" asp-controller="Inbox" asp-action="Index">Почтовый ящик</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Главная</a></li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container-fluid body-content">
        <partial name="_ConfirmEmailPartial" />
        <partial name="_CompanyNamePartial" />
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/vue/vue.js"></script>
        <script src="~/lib/vue/vuetable-2.js"></script>
        <script src="~/lib/uiv/uiv.min.js"></script>
        <script src="~/lib/vue-tags-input/vue-tags-input.js"></script>
        <script src="~/lib/vue-resource/vue-resource.js"></script>
        <script src="~/lib/momentjs/moment.js"></script>
        <script src="~/lib/lodash.js/lodash.js"></script>
        <script src="~/lib/jquery.inputmask/jquery.inputmask.bundle.js"></script>
        <script src="~/lib/axios/axios.js"></script>
        <script src="~/lib/clipboard/clipboard.js"></script>
        <script src="~/lib/numeral.js/numeral.min.js"></script>
        <script src="~/lib/numeral.js/locales/ru.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/bundles/vendor.min.js" asp-append-version="true"></script>
        <script src="~/bundles/custom.min.js" asp-append-version="true"></script>
    </environment>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.9/js/select2.min.js"></script> 
    @RenderSection("Scripts", required: false)
</body>
</html>