DigitalPurchasing.Web/ViewModels/SupplierOffer/SupplierOfferSaveColumnsVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DigitalPurchasing.Core.Interfaces;
using Newtonsoft.Json;

namespace DigitalPurchasing.Web.ViewModels.SupplierOffer
{
    public class SupplierOfferSaveColumnsVm : SupplierOfferColumnsVm
    {
        [JsonProperty("soId")]
        public Guid SupplierOfferId { get; set; }
    }
}

DigitalPurchasing.Web/Controllers/SupplierOfferController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using DigitalPurchasing.Core.Enums;
using DigitalPurchasing.Core.Extensions;
using DigitalPurchasing.Core.Interfaces;
using DigitalPurchasing.Web.ViewModels;
using DigitalPurchasing.Web.ViewModels.SupplierOffer;
using Microsoft.AspNetCore.Mvc;

namespace DigitalPurchasing.Web.Controllers
{
    public class SupplierOfferController : BaseController
    {
        public class UpdateSupplierNameData
        {
            public Guid Id { get; set; }
            public Guid? SupplierId { get; set; }
            public string Name { get; set; }
        }

        public class UpdateDeliveryCostData
        {
            public Guid Id { get; set; }
            public decimal DeliveryCost { get; set; }
        }

        public class SaveMatchItemVm
        {
            public Guid ItemId { get; set; }
            public Guid NomenclatureId { get; set; }
            public Guid UomId { get; set; }
            public decimal FactorN { get; set; }
            public decimal FactorC { get; set; }
            public Guid SupplierId { get; set; }
        }

        private readonly ISupplierOfferService _supplierOfferService;
        private readonly INomenclatureService _nomenclatureService;
        private readonly IUomService _uomService;
        private readonly IRootService _rootService;
        private readonly INomenclatureAlternativeService _nomenclatureAlternativeService;
        private readonly IPurchaseRequestService _purchaseRequestService;

        public SupplierOfferController(
            ISupplierOfferService supplierOfferService,
            INomenclatureService nomenclatureService,
            IUomService uomService,
            IRootService rootService,
            INomenclatureAlternativeService nomenclatureAlternativeService,
            IPurchaseRequestService purchaseRequestService)
        {
            _supplierOfferService = supplierOfferService;
            _nomenclatureService = nomenclatureService;
            _uomService = uomService;
            _rootService = rootService;
            _nomenclatureAlternativeService = nomenclatureAlternativeService;
            _purchaseRequestService = purchaseRequestService;
        }

        public IActionResult Edit(Guid id)
        {
            var vm = _supplierOfferService.GetById(id);

            if (vm.Status == SupplierOfferStatus.MatchColumns)
            {
                return View("EditMatchColumns", vm);
            }

            if (vm.Status == SupplierOfferStatus.MatchItems)
            {
                return View("EditMatchItems", vm);
            }

            return NotFound();
        }

        public IActionResult NomenclatureMappingAutocomplete(Guid supplierOfferId, string q)
        {
            var so = _supplierOfferService.GetById(supplierOfferId);
            var pr = _purchaseRequestService.MatchItemsData(so.PurchaseRequestId);
            var autocompleteResult = _nomenclatureService.Autocomplete(new AutocompleteOptions { Query = q, OwnerId = User.CompanyId() });
            var noms2InPr = from item in autocompleteResult.Items
                            select new
                            {
                                item,
                                inPr = pr.Items.Any(_ => _.NomenclatureId == item.Id)
                            };
            autocompleteResult.Items = noms2InPr.OrderByDescending(_ => _.inPr).Select(_ => _.item).ToList();
            return Json(autocompleteResult);
        }

        [HttpPost]
        public IActionResult UpdateSupplierName([FromBody] UpdateSupplierNameData model)
        {
            _supplierOfferService.UpdateSupplierName(model.Id, model.Name, model.SupplierId);
            return Ok();
        }

        [HttpPost]
        public IActionResult UpdateDeliveryCost([FromBody] UpdateDeliveryCostData model)
        {
            _supplierOfferService.UpdateDeliveryCost(model.Id, model.DeliveryCost);
            return Ok();
        }

        [HttpPost]
        public IActionResult Delete([FromBody] DeleteVm model)
        {
            if (!User.CanDeleteSupplierOffers()) return BadRequest();

            var result = _supplierOfferService.Delete(model.Id);
            if (result.IsSuccess) return Ok();

            return BadRequest();
        }

        #region # MatchColumns

        public IActionResult ColumnsData(Guid id)
        {
            var data = _supplierOfferService.GetColumnsData(id);
            return Ok(data);
        }

        [HttpPost]
        public IActionResult SaveColumns([FromBody] SupplierOfferSaveColumnsVm model)
        {
            _supplierOfferService.SaveColumns(model.SupplierOfferId, model);
            _supplierOfferService.GenerateRawItems(model.SupplierOfferId);
            _supplierOfferService.UpdateStatus(model.SupplierOfferId, SupplierOfferStatus.MatchItems);
            return Ok();
        }

        #endregion

        #region # MatchItems

        [HttpGet]
        public IActionResult MatchItemsData(Guid id)
        {
            var response = _supplierOfferService.MatchItemsData(id);
            return Json(response);
        }

        [HttpPost]
        public async Task<IActionResult> SaveMatchItem([FromBody] SaveMatchItemVm model)
        {
            var companyId = User.CompanyId();
            var fromUomId = model.UomId;
            var nomenclature = _nomenclatureService.GetById(model.NomenclatureId);
            var nomenclatureAlternativeId = _nomenclatureAlternativeService.AddNomenclatureForSupplier(model.ItemId); // must be above than "SaveConversionRate"

            var isSaved = false;

            if (nomenclatureAlternativeId.HasValue && model.FactorN > 0)
            {
                if (fromUomId == nomenclature.MassUomId)
                {
                    // todo: get !1! from uom
                    var mass = 1 / model.FactorN;
                    await _nomenclatureAlternativeService.UpdateMassUom(nomenclatureAlternativeId.Value, fromUomId, mass);
                    isSaved = true;
                }
                else if (fromUomId == await _uomService.GetPackagingUomId(companyId))
                {
                    var quantityInPackage = model.FactorN;
                    await _nomenclatureAlternativeService.UpdatePackUom(nomenclatureAlternativeId.Value, nomenclature.BatchUomId, quantityInPackage);
                    isSaved = true;
                }
            }

            if (!isSaved)
            {
                _uomService.SaveConversionRate(
                    companyId,
                    fromUomId,
                    nomenclature.BatchUomId,
                    nomenclatureAlternativeId,
                    model.FactorC,
                    model.FactorN);
            }

            _supplierOfferService.SaveMatch(model.ItemId, model.NomenclatureId, model.UomId, model.FactorC, model.FactorN);
            
            var clId = await _supplierOfferService.GetCLIdBySoItem(model.ItemId);

            var rootId = await _rootService.GetIdByCL(clId);
            var isAllMatched = _supplierOfferService.IsAllMatchedBySoItem(model.ItemId);
            await _rootService.SetStatus(rootId, isAllMatched
                ? RootStatus.EverythingMatches
                : RootStatus.MatchingRequired);
            
            return Ok();
        }

        #endregion

        #region Details

        public IActionResult Details(Guid id)
        {
            var vm = _supplierOfferService.GetDetailsById(id);
            return View(vm);
        }

        #endregion
    }
}

DigitalPurchasing.Web/Views/SupplierOffer/Details.cshtml
@using DigitalPurchasing.Core
@using DigitalPurchasing.Core.Extensions
@model DigitalPurchasing.Core.Interfaces.SupplierOfferDetailsVm

@{
    ViewBag.Title = $"Подробности КП № {Model.PublicId} от {Model.CreatedOn:dd.MM.yyyy HH:mm}";
    Layout = "_Layout";
}

<h2 class="with-button">@ViewData["Title"]</h2>
<div class="btn-group">
    <a class="btn btn-default" href="@Url.Action("Edit", new { id = Model.Id })">Назад</a>
</div>
<div class="long-table-wrap">
    <div class="long-table">
        <div class="long-table-item">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th colspan="5">Запрос коммерческого предложения</th>
                        <th colspan="7" class="border-left">Коммерческое предложение в полученном варианте</th>
                        <th colspan="5" class="border-left">Расчет доли товара по стоимости и массе в итого</th>
                        <th colspan="3" class="border-left">Пересчет стоимости с учетом доставки @*и таможенной пошлины*@
                        <th colspan="9" class="border-left">Перевод коммерческих условий в ЕИ и валюту запроса</th>
                        <th colspan="7" class="border-left">Пересчет стоимости по количеству в запросе с учетом @*пошлины и*@ доставки и ресурса</th>
                    </tr>
                    <tr>
                        <th>Код</th>
                        <th>Наименование</th>
                        <th>Валюта</th>
                        <th>ЕИ</th>
                        <th>Кол-во,<br />ЕИ</th>

                        <th class="border-left">Код</th>
                        <th>Наименование</th>
                        <th>Валюта КП</th>
                        <th>ЕИ КП</th>
                        <th>Кол-во КП,<br />ЕИ КП</th>
                        <th>Цена в КП,<br />валюта КП за ЕИ КП</th>
                        <th>Стоимость<br />количества КП,<br />валюта КП</th>

                        <th class="border-left">Доля<br />стоимости<br />позиции<br />в общей<br />стоимости</th>
                        <th>Масса 1 ЕИ<br />товара,<br />ед изм массы</th>
                        <th>ЕИ массы</th>
                        <th>Масса<br />количества<br />в заявке,<br />ед массы</th>
                        <th>Доля массы<br />позиции в<br />общей массе</th>

                        @*<th>Таможенная<br />пошлина,<br />проценты</th>
                        <th>Минимальная<br />пошлина,<br />валюта КП<br />за ЕИ КП</th>
                        <th>Таможенная<br />пошлина,<br />в валюте КП</th>*@
                        <th class="border-left">Доставка,<br />валюта КП</th>
                        <th>Стоимость<br />количества в запросе<br />с учетом @*пошлины<br />и*@ доставки,<br />валюта КП</th>
                        <th>Цена с учетом@*<br />пошлины<br />и*@ доставки,<br />валюта запроса<br />за ЕИ КП</th>

                        <th class="border-left">ЕИ<br />запроса</th>
                        <th>ЕИ<br />КП</th>
                        <th>Валюта<br />запроса</th>
                        <th>Валюта<br />КП</th>
                        <th>Коэффициент<br />перевода<br />из ЕИ<br />предложения<br />в ЕИ запроса</th>
                        <th>Курс валют<br />для перевода<br />из валюты КП<br />в валюту<br />запроса</th>
                        <th>Количество<br />в КП,<br />ЕИ запроса</th>
                        <th>Цена в КП,<br />валюта<br />запроса<br />за ЕИ<br />запроса</th>
                        <th>Стоимость<br />количества<br />КП,<br />валюта<br />запроса</th>

                        <th class="border-left">Название ресурса</th>
                        <th>ЕИ<br />ресурса</th>
                        <th>Ресурс<br />товара<br />в КП</th>
                        <th>Ресурс<br />товара<br />в запросе</th>
                        <th>Коэффициент<br />для учета<br />ресурса<br />предложенной<br />позиции в цене</th>
                        <th>Цена с учетом @*пошлины,*@<br />доставки и учетом<br />ресурса по отношению<br />к номенклатуре в запросе,<br />валюта запроса за ЕИ запроса</th>
                        <th>Стоимость количества<br />в запросе с учетом @*пошлины,*@<br />доставки и учетом ресурса<br />по отношению к номенклатуре<br />в запросе, валюта КП</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th colspan="4"></th>
                        <th class="align-right">@Model.Items.Sum(q => q.Request.Qty).ToString(Consts.Format.Qty)</th>

                        <th colspan="4" class="border-left"></th>
                        <th class="align-right">@Model.Items.Sum(q => q.Offer.Qty).ToString(Consts.Format.Qty)</th>
                        <th></th>
                        <th class="align-right">@Model.Items.Sum(q => q.Offer.TotalPrice).ToString(Consts.Format.Money2)</th>

                        <th class="align-right border-left">@Model.Items.Sum(q => q.Mass.TotalPricePerc).ToString("P1")</th>
                        <th colspan="2"></th>
                        <th class="align-right">@Model.Items.Sum(q => q.Mass.TotalMass).ToString(Consts.Format.Money2)</th>
                        <th class="align-right">@Model.Items.Sum(q => q.Mass.TotalMassPerc).ToString("P1")</th>

                        @*<th colspan="2"></th>
                        <th>@Model.Items.Sum(q => q.ImportAndDelivery.CustomsDuty).ToString(Consts.Format.Money)</th>*@
                        <th class="align-right border-left">@Model.Items.Sum(q => q.ImportAndDelivery.DeliveryCost).ToString(Consts.Format.Money2)</th>
                        <th class="align-right">@Model.Items.Sum(q => q.ImportAndDelivery.FinalCost).ToString(Consts.Format.Money2)</th>
                        <th></th>

                        <th colspan="8" class="border-left"></th>
                        <th class="align-right">@Model.Items.Sum(q => q.Conversion.OfferTotalPrice).ToString(Consts.Format.Money2)</th>

                        <th colspan="6" class="border-left"></th>
                        <th class="align-right">@Model.Items.Sum(q => q.ResourceConversion.OfferTotalPrice).ToString(Consts.Format.Money2)</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model.Items.OrderBy(q => q.Position))
                    {
                        <tr>
                            <td>@item.Request.Code</td>
                            <td>@item.Request.Name</td>
                            <td>@item.Request.Currency</td>
                            <td>@item.Request.Uom</td>
                            <td class="align-right">@item.Request.Qty.ToString(Consts.Format.Qty)</td>

                            <td class="border-left">@item.Offer.Code</td>
                            <td>@item.Offer.Name</td>
                            <td>@item.Offer.Currency</td>
                            <td>@item.Offer.Uom</td>
                            <td class="align-right">@item.Offer.Qty.ToString(Consts.Format.Qty)</td>
                            <td class="align-right">@item.Offer.Price.ToString(Consts.Format.Money3)</td>
                            <td class="align-right">@item.Offer.TotalPrice.ToExcelRound(0).ToString(Consts.Format.Money2)</td>

                            <td class="align-right border-left">@item.Mass.TotalPricePerc.ToString("P0")</td>
                            <td class="align-right">@item.Mass.MassOf1BatchUom.ToString(Consts.Format.Money2)</td>
                            <td class="align-right">@item.Mass.MassUom</td>
                            <td class="align-right">@item.Mass.TotalMass.ToString(Consts.Format.Money2)</td>
                            <td class="align-right">@item.Mass.TotalMassPerc.ToString("P0")</td>

                            @*<td>@item.ImportAndDelivery.CustomsDutyPerc.ToString("P1")</td>
                            <td>@item.ImportAndDelivery.MinCustomsDuty.ToString(Consts.Format.Money)</td>
                            <td>@item.ImportAndDelivery.CustomsDuty.ToString(Consts.Format.Money)</td>*@
                            <td class="align-right border-left">@item.ImportAndDelivery.DeliveryCost.ToString(Consts.Format.Money2)</td>
                            <td class="align-right">@item.ImportAndDelivery.FinalCost.ToString(Consts.Format.Money2)</td>
                            <td class="align-right">@item.ImportAndDelivery.FinalCostCostPer1.ToString(Consts.Format.Money2)</td>

                            <td class="border-left">@item.Request.Uom</td>
                            <td>@item.Offer.Uom</td>
                            <td>@item.Request.Currency</td>
                            <td>@item.Offer.Currency</td>
                            <td class="align-right">@item.Conversion.UomRatio.ToString(Consts.Format.Money3)</td>
                            <td class="align-right">@item.Conversion.CurrencyExchangeRate.ToString(Consts.Format.Money2)</td>
                            <td class="align-right">@item.Conversion.OfferQty.ToString(Consts.Format.Money2)</td>
                            <td class="align-right">@item.Conversion.OfferPrice.ToString(Consts.Format.Money2)</td>
                            <td class="align-right">@item.Conversion.OfferTotalPrice.ToString(Consts.Format.Money2)</td>

                            <td class="border-left">@item.ResourceConversion.ResourceUom</td>
                            <td>@item.ResourceConversion.ResourceBatchUom</td>
                            <td>@item.ResourceConversion.OfferResource.ToString(Consts.Format.Money2)</td>
                            <td>@item.ResourceConversion.RequestResource.ToString(Consts.Format.Money2)</td>
                            <td class="align-right">@item.ResourceConversion.ResourceRatio.ToString(Consts.Format.Qty)</td>
                            <td class="align-right">@item.ResourceConversion.OfferPrice.ToString(Consts.Format.Money2)</td>
                            <td class="align-right">@item.ResourceConversion.OfferTotalPrice.ToString(Consts.Format.Money2)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

DigitalPurchasing.Web/Views/SupplierOffer/EditMatchColumns.cshtml
@using DigitalPurchasing.Core.Enums
@using DigitalPurchasing.Core.Interfaces
@model DigitalPurchasing.Core.Interfaces.SupplierOfferVm

@{
    ViewBag.Title = $"Коммерческое предложение № {Model.PublicId} от {Model.CreatedOn:dd.MM.yyyy HH:mm}";
    Layout = "_Layout";
}

<partial name="_Header" model="@((string)ViewBag.Title, Model.CompetitionListId, (Guid?)null)" />

<h3>Сопоставление названия колонок из коммерческого предложения поставщика с названиями колонок системы</h3>
<div id="app">
    <div class="row">
        <div class="col-md-4">
            <div class="form-group" v-bind:class="supplierNameClass">
                <label>Поставщик</label>
                <input type="text" class="form-control" placeholder="" v-model.trim="supplierName" v-on:input="updateSupplierName" id="supplierName" />
                <typeahead v-model="supplierAutocomplete" target="#supplierName" :async-function="supplierAutocompleteFunc" item-key="name"></typeahead>
                <span class="help-block" v-show="supplierNameHasError">Укажите имя поставщика</span>
                <span class="help-block" v-show="isNewSupplier">Новый поставщик</span>
            </div>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Колонки в Системе</th>
            <th>Код</th>
            <th>Наименование</th>
            <th>ЕИ</th>
            <th>Количество</th>
            <th>Цена за 1 ЕИ</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Колонки в Заявке</td>
            <td>
                <select class="form-control" v-model="columnCode">
                    <option v-for="option in columns" v-bind:value="option.value">{{option.text}}</option>
                </select>
            </td>
            <td>
                <select class="form-control" v-model="columnName">
                    <option v-for="option in columns" v-bind:value="option.value">{{option.text}}</option>
                </select>
            </td>
            <td>
                <select class="form-control" v-model="columnUom">
                    <option v-for="option in columns" v-bind:value="option.value">{{option.text}}</option>
                </select>
            </td>
            <td>
                <select class="form-control" v-model="columnQty">
                    <option v-for="option in columns" v-bind:value="option.value">{{option.text}}</option>
                </select>
            </td>
            <td>
                <select class="form-control" v-model="columnPrice">
                    <option v-for="option in columns" v-bind:value="option.value">{{option.text}}</option>
                </select>
            </td>
        </tr>
        </tbody>
    </table>
    <button v-on:click="saveColumns" class="btn btn-primary" v-bind:disabled="isSaveDisabled">Сохранить соответствие столбцов</button>&nbsp;
    <label v-if="isSaved">Сохранено!</label>
</div>

@if (Model.UploadedDocument.Data != null && Model.Status == SupplierOfferStatus.MatchColumns)
{
    <h3>Предложение в формате Поставщика</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                @foreach (var column in Model.ExcelTable.Columns)
                {
                <th>@column.Header</th>
                }
            </tr>
        </thead>
        <tbody>
            @{
                var rowsCount = Model.ExcelTable.Columns.Find(q => q.Type == TableColumnType.Name).Values.Count;
            }
            @for (int i = 0; i < rowsCount; i++)
            {
                <tr>
                    @foreach (var column in Model.ExcelTable.Columns)
                    {
                        <td>@column.Values[i]</td>
                    }
                </tr>
            }
        </tbody>
    </table>
}

@section Scripts
{
    <script>
        (function() {
            function getInputClass(hasError) {
                return {
                    'has-error': hasError,
                    'has-success': !hasError
                };
            };
            var app = new Vue({
                el: '#app',
                data: function() {
                    return {
                        id: '@Model.Id',
                        supplierName: '',
                        supplierId: null,
                        columnCode: null,
                        columnName: null,
                        columnUom: null,
                        columnQty: null,
                        columnPrice: null,
                        columns: [],
                        isSaved: false,
                        supplierAutocomplete: null,
                        saveStarted: false
                    };
                },
                created: function () {
                    var vm = this;
                    vm.$http.get('@Url.Action("ColumnsData", new { id = Model.Id })').then(function(res) {
                        var data = res.body;
                        data.columns.forEach(function(el) {
                            vm.columns.push({ text: el, value: el });
                        });
                        vm.supplierId = data.supplierId;
                        vm.supplierName = data.supplierName;
                        vm.columnCode = data.code;
                        vm.columnName = data.name;
                        vm.columnUom = data.uom;
                        vm.columnQty = data.qty;
                        vm.columnPrice = data.price;
                        vm.isSaved = data.isSaved;
                    }, function(res) {
                        alert('error');
                    });
                },
                watch: {
                    supplierAutocomplete: function(val) {
                        if (val) {
                            if (val.name) {
                                this.supplierName = val.name;
                                this.supplierId = val.id;
                            } else {
                                this.supplierName = this.supplierAutocomplete;
                                this.supplierId = null;
                            }

                        } else {
                            this.supplierName = '';
                            this.supplierId = null;
                        }
                        this.updateSupplierName();
                    }
                },
                computed: {
                    supplierNameHasError: function() {
                        if (!this.supplierName) {
                            return true;
                        }
                        return false;
                    },
                    supplierNameClass: function() {
                        return getInputClass(this.supplierNameHasError);
                    },
                    isSaveDisabled: function() {
                        return this.supplierNameHasError || this.saveStarted;
                    },
                    isNewSupplier: function() {
                        return this.supplierId === null && !this.supplierNameHasError;
                    }
                },
                methods: {
                    saveColumns: function () {
                        this.saveStarted = true;
                        var vm = this;
                        var data = {
                            soId: vm.id,
                            code: vm.columnCode,
                            name: vm.columnName,
                            uom: vm.columnUom,
                            price: vm.columnPrice,
                            qty: vm.columnQty
                        };
                        vm.$http.post('@Url.Action("SaveColumns")', data).then(function (res) {
                            vm.isSaved = true;
                            window.location.reload(true); 
                        }, function (res) {

                        });
                    },
                    supplierAutocompleteFunc (query, done) {
                        var vm = this;
                        vm.$http.get('@Url.Action("Autocomplete", "Supplier")?q=' + query)
                            .then(res => {
                                var items = res.data.items;
                                var supplier = _.find(items, ['name', query]);
                                //console.info(supplier);
                                if (supplier) {
                                    vm.supplierId = supplier.id;
                                    //vm.updateSupplierName();
                                }
                                done(res.data.items);
                            })
                            .catch(err => {
                                // any error handler
                            });
                    },
                    updateSupplierName: _.debounce(function (e) {
                        var data = { name: _.trim(this.supplierName), id: this.id, supplierId: this.supplierId };
                        this.$http.post('@Url.Action("UpdateSupplierName", "SupplierOffer")', data).then(function(res) {
                        }, function(res) {
                            alert('error');
                        });
                    }, 300)
                }
            });
        })();
    </script>
}

DigitalPurchasing.Web/Views/SupplierOffer/_Header.cshtml
@model (string Title, Guid CompetitionListId, Guid? SupplierOfferId)

<div class="row">
    <div class="col-md-12">
        <h2 class="with-button">@Model.Title</h2>
        <div class="btn-group">
            <a class="btn btn-default" asp-action="Edit" asp-controller="CompetitionList" asp-route-id="@Model.CompetitionListId">Назад к конкурентному листу</a>
            @if (Model.SupplierOfferId.HasValue)
            {
                <a class="btn btn-default" asp-action="Details" asp-controller="SupplierOffer" asp-route-id="@Model.SupplierOfferId">Подробности</a>
            }
            @if (User.CanDeleteSupplierOffers())
            {
                <button class="btn btn-default" title="Удалить" data-delete-modal="#modal">
                    <i class="far fa-trash-alt"></i>
                </button>
            }
        </div>
    </div>
</div>

@if (User.CanDeleteSupplierOffers())
{
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Удаление коммерческого предложения</h4>
                </div>
                <div class="modal-body">
                    <p>Удалить "<b>@Model.Title</b>"?</p>
                    <p>Это действие нельзя отменить.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="button" class="btn btn-danger"
                            data-delete-id="@Model.SupplierOfferId"
                            data-delete-url="@Url.Action("Delete", "SupplierOffer")"
                            data-delete-redirect="@Url.Action("Edit","CompetitionList", new { id = Model.CompetitionListId })">Удалить</button>
                </div>
            </div>
        </div>
    </div>
}