DigitalPurchasing.Web/Controllers/AnalysisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DigitalPurchasing.Core.Extensions;
using DigitalPurchasing.Core.Interfaces;
using DigitalPurchasing.Web.ViewModels.Analysis;
using Microsoft.AspNetCore.Mvc;

namespace DigitalPurchasing.Web.Controllers
{
    public class AnalysisController : BaseController
    {
        public class SaveSelectedVariantVm
        {
            public Guid Id { get; set; }
        }

        public class DeleteVariantVm
        {
            public Guid Id { get; set; }
        }

        private readonly IAnalysisService _analysisService;
        private readonly ISelectedSupplierService _selectedSupplierService;

        public AnalysisController(
            IAnalysisService analysisService,
            ISelectedSupplierService selectedSupplierService)
        {
            _analysisService = analysisService;
            _selectedSupplierService = selectedSupplierService;
        }

        [Route("competitionlist/{clId}/analysis")]
        public IActionResult Index(Guid clId)
        {
            var vm = new AnalysisIndexVm
            {
                ClId = clId
            };
            return View(vm);
        }

        [Route("competitionlist/{clId}/analysis/details")]
        public IActionResult Details(Guid clId)
        {
            var data = _analysisService.GetDetails(clId);
            var vm = new AnalysisDetailsVm { ClId = clId, Data = data };
            return View(vm);
        }

        [Route("competitionlist/{clId}/analysisdata")]
        public IActionResult Data(Guid clId) => Json(_analysisService.GetData(clId));

        public IActionResult DefaultVariants() => Json(_analysisService.GetDefaultVariants());

        public IActionResult VariantData(Guid vId) => Json(_analysisService.GetVariantData(vId));

        [HttpPost, Route("competitionlist/{clId}/analysis/add")]
        public IActionResult AddVariant(Guid clId) => Json(_analysisService.AddVariant(clId));

        [HttpPost]
        public IActionResult AddDefaultVariant() => Json(_analysisService.AddDefaultVariant());

        [HttpPost]
        public IActionResult SaveVariant([FromBody]AnalysisSaveVariant vm)
        {
            _analysisService.SaveVariant(vm);
            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> SaveSelectedVariant([FromBody]SaveSelectedVariantVm vm)
        {
            var userId = User.Id();
            var ownerId = User.CompanyId();

            await _analysisService.SelectVariant(vm.Id);
            var result = await _selectedSupplierService.GenerateReportData(ownerId, userId, vm.Id);
            return Ok(new { report = result.IsSuccess });
        }

        [HttpPost]
        public IActionResult DeleteVariant([FromBody]DeleteVariantVm vm)
        {
            _analysisService.DeleteVariant(vm.Id);
            return Ok();
        }
    }
}

DigitalPurchasing.Web/Views/Shared/Variants/_VariantComponent.cshtml
<script type="text/x-template" id="analysis-variant">
    <div class="long-table-item" style="width: 300px;">
        <p class="text-center">
            Вариант {{(index+1)}}
            <button type="button" class="btn btn-default btn-xs" v-on:click="deleteVariant" title="Удалить">
                <i class="far fa-trash-alt"></i>
            </button>
        </p>
        <div>
            <div class="form-group">
                <label for="datetime">Стоимость</label>
                <input type="number" placeholder="0" v-model.number="totalValue" v-on:change="changed" class="form-control">
            </div>
            <div class="form-group">
                <label>Условия оплаты</label>
                <select v-model="paymentTerms" v-on:change="changed" class="form-control">
                    <option v-for="option in paymentTermsOptions" v-bind:value="option.value">{{ option.text }}</option>
                </select>
            </div>
            <div class="form-group">
                <label>Условия доставки</label>
                <select v-model="deliveryTerms" v-on:change="changed" class="form-control">
                    <option v-for="option in deliveryTermsOptions" v-bind:value="option.value">{{ option.text }}</option>
                </select>
            </div>
            <div class="form-group">
                <label>Срок поставки</label>
                <select v-model="deliveryDateTerms" v-on:change="changed" class="form-control">
                    <option v-for="option in deliveryDateTermsOptions" v-bind:value="option.value">{{ option.text }}</option>
                </select>
            </div>
            <div class="form-group">
                <label>Кол-во поставщиков</label>
                <select v-model="supplierCount" v-on:change="changed" class="form-control">
                    <option v-for="option in supplierCountOptions" v-bind:value="option.value">{{ option.text }}</option>
                </select>
            </div>
        </div>
    </div>
</script>

<script>
    (function (vue) {
        vue.component('analysis-variant', {
        template: '#analysis-variant',
        props: ['index', 'id'],
        data: function() {
            return {
                deliveryTerms: 0,
                deliveryTermsOptions: [],
                deliveryDateTerms: 0,
                deliveryDateTermsOptions: [],
                paymentTerms: 0,
                paymentTermsOptions: [],
                supplierCount: 0,
                supplierCountOptions: [],
                totalValue: 0
            }
        },
        methods: {
            loadData: function() {
                this.$http.get('@Url.Action("VariantData", "Analysis")?vId=' + this.id).then(function (response) {
                    var data = response.body;
                    if (data) {
                        this.deliveryTerms = data.deliveryTerms;
                        this.deliveryTermsOptions = data.deliveryTermsOptions;
                        this.deliveryDateTerms = data.deliveryDateTerms;
                        this.deliveryDateTermsOptions = data.deliveryDateTermsOptions;
                        this.paymentTerms = data.paymentTerms;
                        this.paymentTermsOptions = data.paymentTermsOptions;
                        this.supplierCount = data.supplierCount;
                        this.supplierCountOptions = data.supplierCountOptions;
                        this.totalValue = data.totalValue;
                    } else {
                        alert('error');
                    }
                }, function (response) {
                    alert('error');
                });
            },
            changed: function() {
                var vm = this;
                var data = {
                    id: vm.id,
                    deliveryTerms: vm.deliveryTerms,
                    deliveryDateTerms: vm.deliveryDateTerms,
                    paymentTerms: vm.paymentTerms,
                    supplierCount: parseInt(vm.supplierCount.split(':')[0]),
                    supplierCountType: parseInt(vm.supplierCount.split(':')[1]),
                    totalValue: vm.totalValue
                };
                vm.$http.post('@Url.Action("SaveVariant", "Analysis")', data).then(function(response) {
                    vm.$emit('changed', data);
                }, function(response) {
                    alert('Ошибка при сохранении варианта');
                });
            },
            deleteVariant: function() {
                var vm = this;
                var data = {
                    id: vm.id
                };
                vm.$http.post('@Url.Action("DeleteVariant", "Analysis")', data).then(function(response) {
                    this.$emit('deleted');
                }, function(response) {
                    alert('Ошибка при удаление варианта');
                });
            }
        },
        created: function() {
            this.loadData();
        }
    });
    })(Vue)
</script>